### ISSUE TITLE
Links to the different bluetooth product's used would be nice. The youtube video mentions that u bought three and only two worked, but there are additional devices in this code that dont get a mention in the video

### ISSUE THREAD

**Issue by davidbuzz** [SensorsIot/Oximeters-BLE-Hack-ESP32#1]

**Comment by SensorsIot** [comment]
I think I have the links to the products used in the different video descriptions.

**Comment by akeilox** [comment]
is it possible to upload a picture of the Berrymed device that you have tested?
There are few sellers with rather different looking devices with this name.
The IDs match but i think physically there are few versions of this device.
