### ISSUE TITLE
Cannot get values from Oximeter

### ISSUE THREAD

**Issue by dl5dla** [SensorsIot/Oximeters-BLE-Hack-ESP32#4]
Thank you for the code (and the interesting youtube videos around). I am trying now to get my Oximeter (no idea, which brand) working. It seems that the code for Berrymed is most promising. The  output of the sketch shows the following:

`BLE Advertised Device found: Name: F7, Address: c6:a3:29:0a:5b:49, manufacturer data: f0ffc6a3290a5b49, serviceUUID: 0000fee7-0000-1000-8000-00805f9b34fb
Address: c6:a3:29:0a:5b:49
Device has Service UUID
Device is not advertising our Service UUID
Forming a connection to c6:a3:29:0a:5b:49
 - Created client
 - Connected to server
 - Found our service
[E][BLERemoteCharacteristic.cpp:274] retrieveDescriptors(): esp_ble_gattc_get_all_descr: Unknown
 - Found our characteristic 6e400002-b5a3-f393-e0a9-e50e24dcca9e
 - Our characteristic cannot be read.
 - Found our characteristic 6e400003-b5a3-f393-e0a9-e50e24dcca9e
 - Our characteristic cannot be read.
 - Our characteristic can notify us, registering notification callback.
 - Our characteristic cannot indicate.
We are now connected to the BLE Server.`

But there is no output representing the measured values from the Oximeter. I am wondering, whether the message  "Our characteristic cannot be read." is the problem here?

**Comment by dl5dla** [comment]
Some additions:
The device is a Crafish OX-831.
Using the app NRFConnect, I can see, that in the TX section below "Properties: notify", the "Value" is set to "N/A", so I guess the device does not send any data. Can it be that the bytes to switch notify on, is different to "0x01 0x00", as denoted in the sketch?

**Comment by SensorsIot** [comment]
If a device is connected it stops advertising. Then you cannot detect it.
